### PR TITLE
Major upgrade: Support latest versions of Qiskit

### PR DESCRIPTION
**Pull request by hay-k**
Hi,

I have recently (Jun-Jul 2020) [sucessfully passed](https://drive.google.com/file/d/17GXz08-OYb0zTWOU786ujNR-l6C8_adP/view?usp=sharing) the QML MOOC privately held by U of Toronto. A lot has changed in Qiskit since this course materials were created. In particular there are some backward incompatible changes as well as complete API redesign at Qiskit side. Most of the notebooks containing Qiskit code fail with various exceptions if executed against recent versions of Qiskit. To run the course materials one needs a very old version of Qiskit (like something from spring 2019). With this pull request I am upgrading all the notebooks containing Qiskit code (lecture notebooks, assignments and solutions) to support latest version of Qiskit.

I have done the upgrade in a manner, so that the structure and the text in original course materials are preserved as much as possible.

_The most major change addressed by this pull request is:_
* Qiskit Aqua has completely redesigned its operator interface (now called "operator flows") which is almost completely incompatible with the older interface used in the course materials.

Most of the change related to this have gone into the `07_*.ipynb` notebooks, since they have heavy usage of the operator interface in Aqua.

_Other major changes addressed in this pull request are:_
* Qiskit Aqua no longer has the method `get_aer_backend`, so `Aer.get_backend()` should be used instead.
* QuantumCircuit objects no londer have the method `iden()` to add an identity gate: `i()` or `id()` should be used instead.
* `Result` objects no longer support the `eigvecs` property and `eigenstate` should be used instead.

These changes have gone into almost all notebooks.

_Some minor changes:_
* Fix noticed typos.

IMPORTANT NOTES:
* Versions of Qiskit components used to accomplish this pull request: qiskit-terra==0.16.0, qiskit-aer==0.6.1, qiskit-aqua==0.8.0
* In `qiskit_version/07_Variational_Circuits.ipynb`, after running the `minimize` function one expects to see a value close to `-1` as the minimal value of the cost function. With the current version of Qiskit Aqua you will end up with a value close to `-0.25`. This is because of a bug in Qiskit Aqua, and [I have reported it](https://github.com/Qiskit/qiskit-aqua/issues/1324), so it will be fixed in future releases. This is actually just an issue with some coefficients and does not affect the quality of the solution, so the subsequent code blocks work as expected.
* The same bug also affects the output of the `minimize` function in `coding_assignments/solutions/07_Variational_Circuits.ipynb`. With `p=2` it is expected to give something between `-1.5` and `-1`, e.g `-1.13` but it gives something like `-0.28`, and again this is just a coefficient issue and does not affect the quality of the solution. With `p=4` and without the coefficient issue I get exactly `-1.5`, and with the coefficient issue I get `-0.375`.
* The latest Version of Qiskit (i.e. 0.22.0) does not contain the versions of Terra and Aqua used to develop this pull request. With Qiskit v0.22.0 you might face some other bugs as well (I at least know of one). The latest versions of Terra and Aqua not in Qiskit 0.22.0 can be installed manually from github for now, untill a new Qiskit release includes them.

### CODE REVIEW

**Comment by artix41** [comment]
Wow, thank you so much for this super useful pull request! :D I'll try to review it and merge as soon as possible!

**Comment by hay-k** [comment]
@artix41 let me know if any questions arise.

**Comment by hay-k** [comment]
**UPDATE on the IMPORTANT NOTES in the original description of the pull reques**t.

The qiskit version 0.23.0 has been released recently, which contains all bug fixes relevant to this pull request. Thus now `pip` installing the latest version of qiskit (`pip install qiskit==0.23.0`) is enough to run all the notebooks correctly.

**Comment by HuangJunye** [comment]
I was planning to do the same the moment I check out the Qiskit version. @hay-k Well done! @artix41 Can you accept the PR? I think it will be really beneficial to new comers to learn this course with the latest Qiskit version.

**Comment by HuangJunye** [comment]
@artix41 That was quick! Thanks a lot!

**Comment by artix41** [comment]
Thanks for reminding me about it, sorry that it took me so long to accept!

**Pull request merged**
